### PR TITLE
added useNativeDriver to Animated settings

### PR DESCRIPTION
**Pull request by thedigitalnomadagency**
kindly add useNativeDriver to Animated settings

### CODE REVIEW

**Comment by IvanTC95** [comment]
Could this be merged pls?

**Comment by c2tarun** [comment]
Please merge this.

**Comment by paschaldev** [comment]
Merge please

**Comment by MrSinaRJ** [comment]
We really need a merge, even when the screen is reloaded and rating set to something new the warning shows up. please merge **ASAP**.

**Comment by eredessil** [comment]
Merge please. :(

**Comment by eredessil** [comment]
Quick override.  

``` jsx
// CustomRating.js
import React, {PureComponent} from 'react';
import {Animated, StyleSheet, Text, View} from 'react-native';
import _ from 'lodash';

import Star from 'react-native-ratings/src/components/Star';
import {AirbnbRating} from 'react-native-ratings';

export default class FixedStar extends Star {
    constructor(props) {
        super(props);
    }

    spring() {
        const {position, starSelectedInPosition} = this.props;

        this.springValue.setValue(1.2);

        Animated.spring(
            this.springValue,
            {
                toValue: 1,
                friction: 2,
                tension: 1,
                useNativeDriver: true
            }
        ).start();

        this.setState({selected: !this.state.selected});
        starSelectedInPosition(position);
    };
}

export class FixedRating extends AirbnbRating {
    constructor(props) {
        super(props);
    }

    render() {
        const {position} = this.state;
        const {count, reviews, showRating, reviewColor, reviewSize} = this.props;
        const rating_array = [];
        const starContainerStyle = [styles.starContainer];

        if (this.props.starContainerStyle) {
            starContainerStyle.push(this.props.starContainerStyle);
        }

        _.times(count, index => {
            rating_array.push(
                <FixedStar
                    key={index}
                    position={index + 1}
                    starSelectedInPosition={this.starSelectedInPosition.bind(this)}
                    fill={position >= index + 1}
                    {...this.props}
                />
            );
        });

        return (
            <View style={styles.ratingContainer}>
                {showRating &&
                <Text style={[styles.reviewText, {fontSize: reviewSize, color: reviewColor}]}>
                    {reviews[position - 1]}
                </Text>
                }
                <View style={starContainerStyle}>
                    {this.renderStars(rating_array)}
                </View>
            </View>
        );
    }
}

const styles = StyleSheet.create({
    ratingContainer: {
        backgroundColor: 'transparent',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    reviewText: {
        fontWeight: 'bold',
        margin: 10,
    },
    starContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    }
});

```

**Comment by ArjunKarki** [comment]
Merge please. Still getting that warning.Thanks

**Comment by nachozullo** [comment]
Merge please!!

**Comment by MrSinaRJ** [comment]
I reached him yesterday on twitter.
He said that he'll look at it and merge if everything works fine.

**Comment by Monte9** [comment]
Sorry! Merging this in now.

Thanks for the PR and comments! 💯

**Comment by Monte9** [comment]
Released in v7.3.0

**Pull request merged**
