### PR TITLE
fix ratings-style-props tsc issue

### PR DESCRIPTION
**Pull request by khushal87**
Reference issue - #137 
This solves the typescript related issue coming in the apps using the package. Suggestions and comments would be great to improve. Thank you.

### CODE REVIEW

**Review by Monte9 — APPROVED** [review]

**Comment by Monte9** [comment]
LGTM. Thanks for the PR @khushal87! 💯

**Comment by khushal87** [comment]
Glad you liked it <3

**Comment by sshivananda** [comment]
Released in v7.5.0

**Comment by SimenB** [comment]
This gives me an error

```
../../node_modules/react-native-ratings/src/index.d.ts:66:21 - error TS2724: '"/Users/simen/repos/monorepo/node_modules/@types/prop-types/index"' has no exported member named 'object'. Did you mean 'objectOf'?

66   style?: PropTypes.object;
                       ~~~~~~


Found 1 error.
```

**Comment by khushal87** [comment]
> This gives me an error
> 
> ```
> ../../node_modules/react-native-ratings/src/index.d.ts:66:21 - error TS2724: '"/Users/simen/repos/monorepo/node_modules/@types/prop-types/index"' has no exported member named 'object'. Did you mean 'objectOf'?
> 
> 66   style?: PropTypes.object;
>                        ~~~~~~
> 
> 
> Found 1 error.
> ```

Strange, Proptypes.object is a valid proptype definition. Let me check @SimenB

**Comment by stephen776** [comment]
I am seeing the same as @khushal87 at the moment. Was this resolved?

**Comment by khushal87** [comment]
Yes, please upgrade your version, this should work.

**Pull request merged**
