### PR TITLE
TapRating Unselected Icon Tint

### PR DESCRIPTION
**Pull request by benwiebe**
This is a follow-up to PR #100. The default unselected color was changed to white in this version.

In response to comments on the previous PR:
For what I’m looking to accomplish, I have two different variants for my image, one is solid with no outline and one is just an outline. My goal was to just use these two for everything, and so when adapting to a dark device theme I need my outline to change to white (see photos). Rather than add a new asset for that, tinting seemed like a reasonable approach. Hopefully that explains the use case a bit better!

Light-themed rating use-case
Dark-themed rating use-case

### CODE REVIEW

**Comment by sshivananda** [comment]
Can you try this again with the latest published version?

**Comment by sshivananda** [comment]
@benwiebe thanks for the PR - this needs a rebase / merge from master and there's a question on the PR code.

**Comment by benwiebe** [comment]
Will try to find some time in the next few days to get this updated and re-tested!

**Comment by benwiebe** [comment]
Looks like this functionality was included in a different PR already so I will be closing this one. Latest seems to have broken the custom images functionality I had in my local version as well, so may re-raise a PR for that eventually if there's any interest for that again (see #90 )

**Comment by sshivananda** [comment]
Awesome - if you can get the custom image functionality PR up - would be happy to test/ release it

**Pull request closed without merging**
