### PR TITLE
add "starStyle" props

### PR DESCRIPTION
**Pull request by KangYoosam**
resolve https://github.com/Monte9/react-native-ratings/issues/53

## What
Able to pass "startStyle" prop, it is useful if we want to customize style of `Star` component. Especially space between stars.

### CODE REVIEW

**Comment by ramaguduri** [comment]
Can we have the same feature in Star component as well?

**Comment by Monte9** [comment]
Sure, I'll take a look at this in the next couple days and merge it in.

**Comment by aevzp** [comment]
When we can get this update? =)

**Comment by Monte9** [comment]
thanks for submitting a PR @KangYoosam!

**Comment by Monte9** [comment]
Released in v6.4.0

**Pull request merged**
