### PR TITLE
Update Star.js

### PR DESCRIPTION
**Pull request by Amirnajafi**
fixed start change color problem on android

### CODE REVIEW

**Review by adrielschmitz — APPROVED** [review]

**Comment by thomasgrivet** [comment]
Hello, can this PR be merged? It would fix the issue we have on Android. ➡️ https://github.com/Monte9/react-native-ratings/issues/126#issuecomment-713485434_ Thanks!

**Comment by RedekProject** [comment]
Good evening, would it be possible to perform a merge in order to solve this bug which is very annoying ?

**Comment by JnnyRdng** [comment]
Should it not be a string?

I'd rather see https://github.com/Monte9/react-native-ratings/pull/121 get merged anyway, which would fix this issue while giving some control over the unfilled colour.

**Comment by RedekProject** [comment]
> Should it not be a string?
> 
> I'd rather see #121 get merged anyway, which would fix this issue while giving some control over the unfilled colour.

Ah yes indeed it would have to be a thong. So it would be better to merge the pull request you stipulated.

**Comment by sshivananda** [comment]
Closing this - #121  is merged.

**Pull request closed without merging**
