### PR TITLE
Fix image assets import issue

### PR DESCRIPTION
**Pull request by khushal87**
Fixes -  #145

### CODE REVIEW

**Comment by khushal87** [comment]
@sshivananda Please review this PR on priority. Many users are facing issue.

**Comment by sshivananda** [comment]
Take a look at #147 
In an upcoming release - only the dist folder will be published (to npm) : I have added a post build script to copy the images to the dist folder

**Comment by khushal87** [comment]
Okay, then I am closing this PR.

**Comment by sshivananda** [comment]
I have seen both implementations 
- having images in a separate folder
- including images with the dist folder

Here's my opinion

- the dist folder is what is packaged as the distributable (similar to the dmg file) and should contain everything that is needed to run the application

**Comment by khushal87** [comment]
Yes according to me both are fine, its your call you can choose any. @sshivananda

**Pull request closed without merging**
